name: Deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: Roblox/setup-foreman@v1
        name: Install Foreman
        with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - run: rojo build -o game.rblx
      - run:  rbxcloud experience publish --filename game.rbxl --place-id 17561650808 --universe-id 6011805381 --version-type published --api-key ${{ secrets.API_KEY }}
